version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Ensure your application uses the correct profile

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:9090  # Make frontend use backend service name
    depends_on:
      - backend  # Only frontend depends on backend (No circular dependency)
