version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=9090
      - SERVER_ADDRESS=0.0.0.0
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:9090
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
