version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod  

  frontend:
    build: ./client
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:9090
    depends_on:
      - backend
