name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY_BACKEND: ${{ secrets.ECR_REPOSITORY_BACKEND }}
  ECR_REPOSITORY_FRONTEND: ${{ secrets.ECR_REPOSITORY_FRONTEND }}
  ELASTIC_BEANSTALK_ENVIRONMENT: ${{ secrets.ELASTIC_BEANSTALK_ENVIRONMENT }}
  ELASTIC_BEANSTALK_APPLICATION: ${{ secrets.ELASTIC_BEANSTALK_APPLICATION }}

jobs:
  deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Login to AWS ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_BACKEND
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_FRONTEND

      # Build and push backend Docker image
      - name: Build and push Backend Docker image
        run: |
          docker build -t backend ./backend
          docker tag backend:latest $ECR_REPOSITORY_BACKEND:latest
          docker push $ECR_REPOSITORY_BACKEND:latest

      # Build and push frontend Docker image
      - name: Build and push Frontend Docker image
        run: |
          docker build -t frontend ./client
          docker tag frontend:latest $ECR_REPOSITORY_FRONTEND:latest
          docker push $ECR_REPOSITORY_FRONTEND:latest

      # Deploy to AWS Elastic Beanstalk
      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment --application-name $ELASTIC_BEANSTALK_APPLICATION \
            --environment-name $ELASTIC_BEANSTALK_ENVIRONMENT \
            --version-label "$(date +'%Y%m%d%H%M%S')"
